import React, { useEffect, useState } from 'react'
import { fetchHistory } from '../api'

export default function HistoryPage() {
  const [history, setHistory] = useState([])

  useEffect(() => {
    fetchHistory().then((data) => setHistory(data.history || []))
  }, [])

  return (
    <div className="container section">
      <div className="card table-wrap">
        <span className="badge">Decision Records</span>
        <h2>Decision History</h2>
        <p className="subtitle">
          Review previous recommendations generated by Ka-ching AI.
        </p>

        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Recommended Option</th>
              <th>Sector</th>
              <th>Goal</th>
              <th>Confidence</th>
              <th>AI Mode</th>
              <th>Created At</th>
            </tr>
          </thead>

          <tbody>
            {history.map((item) => (
              <tr key={item.id}>
                <td>{item.id}</td>
                <td>{item.recommended_option}</td>
                <td>{item.company_field}</td>
                <td>{item.goal}</td>
                <td>{item.confidence_score}%</td>
                <td>{item.ai_mode}</td>
                <td>{item.created_at}</td>
              </tr>
            ))}

            {!history.length && (
              <tr>
                <td colSpan="7">No history yet. Run an analysis first.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}